version: "3"

services:
  qa-web-application-2:
    image: jamie050401/qa-web-application-2:latest
    container_name: qa-web-application-2
    restart: always
    ports:
      - 5000:5000/tcp
    environment:
      - QAWA-Cookie-Secret=${QAWA-Cookie-Secret}
    volumes:
      - /docker/app/data/database.sqlite:/app/Data/database.sqlite
