name: Build/Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Build-Test:
    uses: ./.github/workflows/reusable/build-test.yml
    with:
      github-workspace: ${{ github.workspace }}
    secrets: inherit
