name: main

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Build-Test:
    uses: ./.github/workflows/reusable-build-test.yml
    secrets: inherit

  Static-Analysis:
    uses: ./.github/workflows/reusable-static-analysis.yml
    secrets: inherit
