name: Reusable Deploy

on:
  workflow_call:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: "main"
    # TODO - Need to be able to destroy the stack 'qa-web-application-2' if it already exists
    - name: Deploy to Portainer
      run: |
        curl -X POST -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" \
        -F "Name=qa-web-application-2" \
        -F "Env=[{\"name\": \"QAWA-Cookie-Secret\", \"value\": \"${{ secrets.QAWA_Cookie_Secret }}\"}]" \
        -F "file=@./docker-compose.yml" \
        "${{ secrets.PORTAINER_HOST }}/api/stacks/create/standalone/file?endpointId=${{ secrets.PORTAINER_ENV_ID }}"
