name: Reusable Static Analysis

on:
  workflow_call:

jobs:
  Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
          fetch-depth: 0
      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          pr-mode: false
          args: --baseline,qodana.sarif.json,--apply-fixes
          push-fixes: pull-request
          upload-result: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
