name: Reusable Static Analysis

on:
  workflow_call:
    inputs:
      git-branch:
        required: true
        type: string

jobs:
  Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-branch }}
          fetch-depth: 0
      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          pr-mode: false
          args: --baseline,qodana.sarif.json,--apply-fixes
          push-fixes: pull-request
          upload-result: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
