name: Reusable Deploy

on:
  workflow_call:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: "main"
    - name: Deploy to Portainer
      run: |
        curl -X POST -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" \
        -F "Name=qa-web-application-2" \
        -F "Env=[{\"name\": \"QAWA-Cookie-Secret\", \"value\": \"${{ secrets.QAWA_Cookie_Secret }}\"}]" \
        -F "file=@./docker-compose.yml" \
        "${{ secrets.PORTAINER_HOST }}/api/stacks/create/standalone/file?endpointId=${{ secrets.PORTAINER_ENV_ID }}"

    #  uses: datntdev0/action-deploy-to-portainer@v0.1.0
    #  with:
    #      portainerHost: ${{ secrets.PORTAINER_HOST }}
    #      portainerApiKey: ${{ secrets.PORTAINER_API_KEY }}
    #      portainerEnvId: ${{ secrets.PORTAINER_ENV_ID }}
    #      portainerStackName: 'qa-web-application-2'
    #      portainerFilePath: './docker-compose.yml'
    #      portainerEnvVars: '[{"QAWA-Cookie-Secret": "${{ secrets.QAWA_Cookie_Secret }}"}]'
