name: Reusable Deploy

on:
  workflow_call:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: "main"
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install -y jq
    - name: Destroy existing stack
      shell: bash
      run: |
        stacks=$(curl -X GET -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" "${{ secrets.PORTAINER_HOST }}/api/stacks")
        stack=$(echo $stacks | jq '.[] | select(.Name=="qa-web-application-2")')
        id=$(echo $stack | jq -r '.Id')
        curl -X DELETE -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" "${{ secrets.PORTAINER_HOST }}/api/stacks/$id?endpointId=${{ secrets.PORTAINER_ENV_ID }}"
        sleep 1
        curl -X DELETE -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" "${{ secrets.PORTAINER_HOST }}/api/endpoints/${{ secrets.PORTAINER_ENV_ID }}/docker/images/jamie050401/qa-web-application-2:latest"
        sleep 1
    - name: Deploy to Portainer
      shell: bash
      run: |
        curl -X POST -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" \
        -F "Name=qa-web-application-2" \
        -F "Env=[{\"name\": \"QAWA-Cookie-Secret\", \"value\": \"${{ secrets.QAWA_Cookie_Secret }}\"}]" \
        -F "file=@./docker-compose.yml" \
        "${{ secrets.PORTAINER_HOST }}/api/stacks/create/standalone/file?endpointId=${{ secrets.PORTAINER_ENV_ID }}"
